### PR TITLE
Mention that CONTRIBUTORS.txt doesn't apply to all repos

### PR DESCRIPTION
**Pull request by Mariatta**
## What do these changes do?

In Global PR template, mention that the CONTRIBUTORS.txt doesn't always exist.
It can be skipped/ignored if there is no such file.

## Are there changes in behavior for the user?

Contributors will see a different PR template

## Related issue number

N/A

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is `<Name> <Surname>`.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by asvetlov** [comment]
IFAIK only aiohttp has `CONTRIBUTORS.txt` but aiohttp provides own PR template.
Maybe just drop mentions of `CONTRIBUTORS.txt` from this generic version?

**Comment by Mariatta** [comment]
aioredis also has contributors.txt

**Comment by webknjaz** [comment]
Ideally, repos should have their specific templates and this one should be used only as a fallback.

**Comment by Mariatta** [comment]
I created an alternative PR #3 and added a template specific to aioredis https://github.com/aio-libs/aioredis/pull/600

**Comment by asvetlov** [comment]
I prefer #3 because that version doesn't require searching for `CONTRIBUTORS.txt` to figure out that the file is missing.
In other words, #3 is more obvious for newcomers I think

**Pull request closed without merging**
